#!/bin/sh

rdarcs () {
    (cd ${REPODIR:-.}; ${DARCS:-darcs} $@)
}

tag=$(rdarcs show tag | head -n1 | tr -d \\n)
patches=$(expr $(rdarcs changes --from-tag "$tag" --count) - 1)
hash=$(rdarcs show index | grep ' ./$' | sed 's/^\(........\).*/\1/')

echo -n $tag
case $patches in
    0) break;;
    1) echo -n " + 1 patch"; break;;
    *) echo -n " + $patches patches"; break;;
esac
echo " $hash"
