#!/bin/sh

tag=$($DARCS show tag | head -n1 | tr -d \\n)
patches=$(expr $($DARCS changes --from-tag $tag --count) - 1)

echo -n $tag
case $patches in
    0) break;;
    1) echo -n " + 1 patch"; break;;
    *) echo -n " + $patches patches"; break;;
esac
